name = "The Beast Churns"
author = "Grace"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0622ddff116df065decbb313e94a5f982fcc8cc8818b63ccc521537719204011"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
