name = "The Beast Churns"
author = "Grace"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e517705c907809413f5a5699460dd01c3fd0797bfe39930d32ae06160bc61d92"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.2"]
